apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-api-service
  namespace: patch-portal-{{ .Values.environment.name }}
  labels:
    app: {{ .Values.applicationName }}
    chart: {{ template "patch-portal.chart" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
  selector:
    app: {{ template "patch-portal.fullname" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
